### ISSUE TITLE
Bevy's Third Birthday post date is incorrect

### ISSUE THREAD

**Issue by dvergeylen** [JMS55/jms55.github.io#2]
Hi,

Thank you for your post (came across from Bevy's website). I know this is very pedantic, but I think your blogpost date is incorrect, your blog engine reads YYYY-DD-MM, not YYYY-MM-DD (→ December 2023 instead of September 2023). It shows in the Archive tab.

Anyway thanks for the good work on Bevy and looking for other posts (like: what do you do for a living, do you work fulltime on Bevy through donations?)! :wave:

**Comment by JMS55** [comment]
Hi, thanks for the bug report! I've fixed it now.

It's unlikely that I'll write more posts in the near future, but to answer your questions:
* At the moment I do generic software development, nothing related to gamedev or bevy
* I'm not sponsored in any way to work on bevy
